# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 21:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GrandesAreas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Instituicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('localizacao', models.CharField(max_length=200)),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='servidor.GrandesAreas')),
            ],
        ),
        migrations.CreateModel(
            name='MediasAreas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('grande_area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='servidor.GrandesAreas')),
            ],
        ),
        migrations.CreateModel(
            name='PequenasAreas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('media_area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='servidor.MediasAreas')),
            ],
        ),
        migrations.CreateModel(
            name='Pesquisa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abstract', models.TextField()),
                ('tags', models.TextField()),
                ('pequena_area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='servidor.PequenasAreas')),
            ],
        ),
        migrations.CreateModel(
            name='Pesquisador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('nivel', models.CharField(max_length=100)),
                ('area_conhecimento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='servidor.MediasAreas')),
                ('instituicao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='servidor.Instituicao')),
            ],
        ),
        migrations.AddField(
            model_name='pesquisa',
            name='pesquisadores',
            field=models.ManyToManyField(to='servidor.Pesquisador'),
        ),
    ]
