# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 22:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servidor', '0003_campus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instituicao',
            name='localizacao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='servidor.Campus'),
        ),
    ]
