# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 00:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servidor', '0004_auto_20170819_2229'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrauDeInstrucao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, default='nome', max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
