# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 00:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servidor', '0006_auto_20170820_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesquisador',
            name='instituicao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='servidor.Instituicao'),
        ),
    ]
