# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 07:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servidor', '0007_pesquisador_instituicao'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesquisa',
            name='nivel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='servidor.GrauDeInstrucao'),
        ),
    ]
