# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servidor', '0008_pesquisa_nivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesquisa',
            name='bibliografia',
            field=models.ManyToManyField(blank=True, related_name='_pesquisa_bibliografia_+', to='servidor.Pesquisa'),
        ),
    ]
