# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servidor', '0009_pesquisa_bibliografia'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesquisa',
            name='end',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='pesquisa',
            name='start',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='pesquisa',
            name='titulo',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pesquisador',
            name='email',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pesquisador',
            name='sala',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='campus',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='grandesareas',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='graudeinstrucao',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='instituicao',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mediasareas',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pequenasareas',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pesquisa',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pesquisador',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
