# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servidor', '0014_auto_20170820_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesquisa',
            name='end',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='pesquisa',
            name='start',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='pesquisador',
            name='email',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pesquisador',
            name='sala',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
