# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servidor', '0015_auto_20170820_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesquisa',
            name='titulo',
            field=models.TextField(null=True),
        ),
    ]
