# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 12:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servidor', '0010_auto_20170820_1153'),
        ('servidor', '0016_pesquisa_titulo'),
    ]

    operations = [
    ]
